# Site settings
title: The Palm Beaches
client:
  name: Urlaub der Extraklasse
  link: "https://www.thepalmbeaches.com/"
core-se-link: https://www.secretescapes.de
se-tracking-link: ""
description: >
  Entdecken Sie Instagramreife Tipps für Jetsetter, die schönsten Orte für Strandliebhaber, exklusivsten Adressen für Luxusreisende und unvergessliche Erfahrungen für Abenteurer.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/the-palm-beaches" # the subpath of your site, e.g. /blog/
img:     "/de/the-palm-beaches/_assets/img"
css:     "/de/the-palm-beaches/_assets/css"
js:      "/de/the-palm-beaches/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
